package com.thinkai.schema;

import java.util.Locale;
import java.util.regex.Pattern;

/**
 * JDBC metadata reports identity/serial columns as INT8/INT4 and drops
 * {@code nextval} from CREATE TABLE. SchemaApplier then creates tables whose
 * {@code INSERT} leaves {@code id} null. Restore a sequence-backed type for
 * surrogate {@code id} primary keys only — never for FKs.
 *
 * <p>Repair invariants (existing tables):
 * <ul>
 *   <li>Attach IDENTITY and {@code setval} in one transaction.</li>
 *   <li>{@code LOCK TABLE ... SHARE ROW EXCLUSIVE} so concurrent INSERTs wait;
 *       {@code MAX(id)} cannot go stale under another replica.</li>
 *   <li>{@code setval(GREATEST(last_value, MAX(id)))} never rewinds a sequence
 *       that is already ahead of the table.</li>
 *   <li>Empty tables are not {@code setval}'d (identity already starts at 1).</li>
 *   <li>Only sole {@code PRIMARY KEY (id)} — not composite keys.</li>
 * </ul>
 */
public final class PkIdentity {

    private static final Pattern SOLE_ID_PK = Pattern.compile("PRIMARY KEY \\(ID\\)", Pattern.CASE_INSENSITIVE);

    public static String lockTableSql(String tableName) {
        return "LOCK TABLE " + quoteIdent(tableName) + " IN SHARE ROW EXCLUSIVE MODE";
    }

    public static String addGeneratedIdentitySql(String tableName) {
        String t = quoteIdent(tableName);
        return "ALTER TABLE " + t + " ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY";
    }

    /**
     * Advance the sequence to at least {@code MAX(id)}, never below {@code last_value}.
     * Empty table: third argument false so the next value stays 1.
     */
    public static String syncIdentitySequenceSql(String tableName) {
        String t = quoteIdent(tableName);
        String seq = "pg_get_serial_sequence('" + tableName + "', 'id')";
        return "SELECT setval(" + seq + ", "
                + "GREATEST("
                + "COALESCE((SELECT s.last_value FROM pg_sequences s "
                + "WHERE (s.schemaname || '.' || s.sequencename) = " + seq + "), 1), "
                + "COALESCE((SELECT MAX(id) FROM " + t + "), 1)"
                + "), "
                + "(SELECT MAX(id) FROM " + t + ") IS NOT NULL)";
    }

    public static String quoteIdent(String tableName) {
        if (tableName == null || !tableName.matches("[a-z][a-z0-9_]*")) {
            throw new IllegalArgumentException("invalid table name: " + tableName);
        }
        return tableName;
    }

    public static boolean needsSequenceAdvance(Long seqLastValue, Long maxId) {
        if (maxId == null) {
            return false;
        }
        if (seqLastValue == null) {
            return true;
        }
        return seqLastValue <= maxId;
    }

    public static String readSequenceStateSql(String tableName) {
        String t = quoteIdent(tableName);
        return "SELECT s.last_value, (SELECT MAX(id) FROM " + t + ") AS max_id "
                + "FROM pg_sequences s "
                + "WHERE (s.schemaname || '.' || s.sequencename) = pg_get_serial_sequence('"
                + tableName + "', 'id')";
    }

    public static boolean needsIdentityRepair(String attidentity, String serialSequence) {
        if (attidentity != null && !attidentity.isBlank()) {
            return false;
        }
        return serialSequence == null || serialSequence.isBlank();
    }

    public static boolean hasSoleIdPrimaryKey(String createSql) {
        return createSql != null && SOLE_ID_PK.matcher(createSql).find();
    }

    public static boolean createSqlWantsIdIdentity(String createSql) {
        if (!hasSoleIdPrimaryKey(createSql)) {
            return false;
        }
        String upper = createSql.toUpperCase(Locale.ROOT);
        return upper.contains("ID BIGSERIAL") || upper.contains("ID SERIAL")
                || upper.contains("GENERATED BY DEFAULT AS IDENTITY")
                || upper.contains("GENERATED ALWAYS AS IDENTITY");
    }

    public static String createType(String typeName, String nullable, String columnDefault,
                             boolean autoIncrement, boolean primaryKey) {
        if (isSequenceBackedInteger(typeName, columnDefault, autoIncrement)) {
            return serialKeyword(typeName) + nullable;
        }
        String base = switch (typeName) {
            case "BIGSERIAL", "SERIAL" -> typeName;
            case "INT2" -> "SMALLINT";
            default -> typeName;
        };
        base += nullable;
        if (columnDefault != null && !columnDefault.contains("nextval(")) {
            base += " DEFAULT " + columnDefault;
        }
        return base;
    }

    public static boolean isSequenceBackedInteger(String typeName, String columnDefault, boolean autoIncrement) {
        if (!isIntegerFamily(typeName)) {
            return false;
        }
        return autoIncrement || (columnDefault != null && columnDefault.contains("nextval("));
    }

    public static String restoreCreateSql(String createSql) {
        if (!hasSoleIdPrimaryKey(createSql)) {
            return createSql;
        }
        return createSql
                .replaceFirst("(?i)\\bid INT8 NOT NULL\\b", "id BIGSERIAL NOT NULL")
                .replaceFirst("(?i)\\bid BIGINT NOT NULL\\b", "id BIGSERIAL NOT NULL")
                .replaceFirst("(?i)\\bid INT4 NOT NULL\\b", "id SERIAL NOT NULL")
                .replaceFirst("(?i)\\bid INTEGER NOT NULL\\b", "id SERIAL NOT NULL");
    }

    public static String restoreIdColumnDefinition(String columnName, String definition, String createSql) {
        if (definition == null || !"id".equalsIgnoreCase(columnName) || createSql == null) {
            return definition;
        }
        String sql = restoreCreateSql(createSql).toUpperCase(Locale.ROOT);
        String def = definition;
        if (sql.contains("ID BIGSERIAL NOT NULL") && def.toUpperCase(Locale.ROOT).startsWith("INT8 NOT NULL")) {
            return "BIGSERIAL" + def.substring("INT8".length());
        }
        if (sql.contains("ID BIGSERIAL NOT NULL") && def.toUpperCase(Locale.ROOT).startsWith("BIGINT NOT NULL")) {
            return "BIGSERIAL" + def.substring("BIGINT".length());
        }
        if (sql.contains("ID SERIAL NOT NULL") && def.toUpperCase(Locale.ROOT).startsWith("INT4 NOT NULL")) {
            return "SERIAL" + def.substring("INT4".length());
        }
        if (sql.contains("ID SERIAL NOT NULL") && def.toUpperCase(Locale.ROOT).startsWith("INTEGER NOT NULL")) {
            return "SERIAL" + def.substring("INTEGER".length());
        }
        return definition;
    }

    private static boolean isIntegerFamily(String typeName) {
        if (typeName == null) {
            return false;
        }
        String t = typeName.toUpperCase(Locale.ROOT);
        return "INT8".equals(t) || "BIGINT".equals(t) || "INT4".equals(t)
                || "INTEGER".equals(t) || "INT".equals(t);
    }

    private static String serialKeyword(String typeName) {
        String t = typeName.toUpperCase(Locale.ROOT);
        if ("INT4".equals(t) || "INTEGER".equals(t) || "INT".equals(t)) {
            return "SERIAL";
        }
        return "BIGSERIAL";
    }
}
