// Copyright 2026 ThinkAI LLC
// SPDX-License-Identifier: Apache-2.0

package com.thinkaillc.schemasynchronizer;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;

/** Dialect-specific locking and history DDL helpers. */
final class DialectSupport {
    private DialectSupport() {
    }

    static String createHistoryDdl(DatabaseDialect dialect, String qualifiedHistory) {
        return switch (dialect) {
            case POSTGRESQL -> "CREATE TABLE IF NOT EXISTS " + qualifiedHistory + " ("
                    + "installed_rank BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "change_id VARCHAR(200) NOT NULL UNIQUE, "
                    + "checksum CHAR(64) NOT NULL, "
                    + "description VARCHAR(500), "
                    + "applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, "
                    + "execution_ms BIGINT NOT NULL)";
            case MARIADB, MYSQL -> "CREATE TABLE IF NOT EXISTS " + qualifiedHistory + " ("
                    + "installed_rank BIGINT AUTO_INCREMENT PRIMARY KEY, "
                    + "change_id VARCHAR(200) NOT NULL UNIQUE, "
                    + "checksum CHAR(64) NOT NULL, "
                    + "description VARCHAR(500), "
                    + "applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "
                    + "execution_ms BIGINT NOT NULL)";
            case SQLSERVER -> "IF OBJECT_ID(N'" + escapeSqlServerLiteral(qualifiedHistory) + "', N'U') IS NULL "
                    + "CREATE TABLE " + qualifiedHistory + " ("
                    + "installed_rank BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY, "
                    + "change_id VARCHAR(200) NOT NULL UNIQUE, "
                    + "checksum CHAR(64) NOT NULL, "
                    + "description VARCHAR(500) NULL, "
                    + "applied_at DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(), "
                    + "execution_ms BIGINT NOT NULL)";
            case ORACLE -> "BEGIN EXECUTE IMMEDIATE 'CREATE TABLE " + qualifiedHistory + " ("
                    + "installed_rank NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "change_id VARCHAR2(200) NOT NULL UNIQUE, "
                    + "checksum CHAR(64) NOT NULL, "
                    + "description VARCHAR2(500), "
                    + "applied_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL, "
                    + "execution_ms NUMBER NOT NULL)'; "
                    + "EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;";
        };
    }

    /**
     * Acquires an exclusive synchronization lock. Returns a token for {@link #releaseLock}
     * (may be {@code null} when the dialect uses transaction-scoped locks).
     */
    static String acquireLock(Connection conn, DatabaseDialect dialect, String namespace, long advisoryLockId)
            throws SQLException {
        return switch (dialect) {
            case POSTGRESQL -> {
                try (Statement statement = conn.createStatement()) {
                    statement.execute("SELECT pg_advisory_xact_lock(" + advisoryLockId + ")");
                }
                yield null;
            }
            case MARIADB, MYSQL -> {
                String resource = "schema_synchronizer_" + namespace;
                try (var statement = conn.prepareStatement("SELECT GET_LOCK(?, 30)")) {
                    statement.setString(1, resource);
                    try (var row = statement.executeQuery()) {
                        if (!(row.next() && row.getInt(1) == 1)) {
                            throw new IllegalStateException("Could not acquire " + dialect.id()
                                    + " schema synchronization lock");
                        }
                    }
                }
                yield resource;
            }
            case SQLSERVER -> {
                String resource = "schema_synchronizer_" + namespace;
                try (var statement = conn.prepareStatement(
                        "DECLARE @result INT; "
                                + "EXEC @result = sp_getapplock @Resource = ?, @LockMode = 'Exclusive', "
                                + "@LockOwner = 'Session', @LockTimeout = 30000; "
                                + "SELECT @result")) {
                    statement.setString(1, resource);
                    try (var row = statement.executeQuery()) {
                        if (!row.next() || row.getInt(1) < 0) {
                            throw new IllegalStateException(
                                    "Could not acquire sqlserver schema synchronization lock");
                        }
                    }
                }
                yield resource;
            }
            case ORACLE -> {
                int lockId = Math.floorMod(Long.hashCode(advisoryLockId), 1_073_741_823);
                try (var statement = conn.prepareCall("{ ? = call DBMS_LOCK.REQUEST(?, 6, 30, true) }")) {
                    statement.registerOutParameter(1, Types.INTEGER);
                    statement.setInt(2, lockId);
                    statement.execute();
                    int status = statement.getInt(1);
                    // 0 = success, 4 = already owned by this session
                    if (status != 0 && status != 4) {
                        throw new IllegalStateException(
                                "Could not acquire oracle schema synchronization lock (status=" + status + ")");
                    }
                }
                yield Integer.toString(lockId);
            }
        };
    }

    static void releaseLock(Connection conn, DatabaseDialect dialect, String lockToken) throws SQLException {
        if (lockToken == null || lockToken.isBlank()) {
            return;
        }
        switch (dialect) {
            case MARIADB, MYSQL -> {
                try (var statement = conn.prepareStatement("SELECT RELEASE_LOCK(?)")) {
                    statement.setString(1, lockToken);
                    statement.executeQuery().close();
                }
            }
            case SQLSERVER -> {
                try (var statement = conn.prepareStatement(
                        "DECLARE @result INT; "
                                + "EXEC @result = sp_releaseapplock @Resource = ?, @LockOwner = 'Session'; "
                                + "SELECT @result")) {
                    statement.setString(1, lockToken);
                    statement.executeQuery().close();
                }
            }
            case ORACLE -> {
                int lockId = Integer.parseInt(lockToken);
                try (var statement = conn.prepareCall("{ ? = call DBMS_LOCK.RELEASE(?) }")) {
                    statement.registerOutParameter(1, Types.INTEGER);
                    statement.setInt(2, lockId);
                    statement.execute();
                    int status = statement.getInt(1);
                    // 0 = success, 3 = parameter error ignored when lock already gone, 4 = do not own
                    if (status != 0 && status != 3 && status != 4) {
                        throw new SQLException("Could not release oracle schema synchronization lock (status="
                                + status + ")");
                    }
                }
            }
            case POSTGRESQL -> {
                // transaction-scoped advisory lock released on commit/rollback
            }
        }
    }

    private static String escapeSqlServerLiteral(String value) {
        return value.replace("'", "''");
    }
}
