// Copyright 2026 ThinkAI LLC
// SPDX-License-Identifier: Apache-2.0

package com.thinkaillc.schemasynchronizer;

import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.util.ArrayList;
import java.util.HexFormat;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Objects;
import java.util.Set;
import java.util.concurrent.TimeUnit;

/** Dialect-specific locking and history DDL helpers. */
final class DialectSupport {
    /** MySQL GET_LOCK resource names truncate at 64 characters. */
    static final int MYSQL_LOCK_NAME_MAX = 64;
    /** Total time {@link #acquireLock} waits for all of a run's locks. */
    static final long LOCK_WAIT_SECONDS = 30;

    private DialectSupport() {
    }

    static String createHistoryDdl(DatabaseDialect dialect, String qualifiedHistory) {
        String installedRank = SqlIdentifiers.quote(dialect, "installed_rank");
        String changeId = SqlIdentifiers.quote(dialect, "change_id");
        String checksum = SqlIdentifiers.quote(dialect, "checksum");
        String description = SqlIdentifiers.quote(dialect, "description");
        String appliedBy = SqlIdentifiers.quote(dialect, "applied_by");
        String appliedAt = SqlIdentifiers.quote(dialect, "applied_at");
        String executionMs = SqlIdentifiers.quote(dialect, "execution_ms");
        return switch (dialect) {
            case POSTGRESQL -> "CREATE TABLE IF NOT EXISTS " + qualifiedHistory + " ("
                    + installedRank + " BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + changeId + " VARCHAR(200) NOT NULL UNIQUE, "
                    + checksum + " CHAR(64) NOT NULL, "
                    + description + " VARCHAR(500), "
                    + appliedBy + " VARCHAR(200), "
                    + appliedAt + " TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, "
                    + executionMs + " BIGINT NOT NULL)";
            case MARIADB, MYSQL -> "CREATE TABLE IF NOT EXISTS " + qualifiedHistory + " ("
                    + installedRank + " BIGINT AUTO_INCREMENT PRIMARY KEY, "
                    + changeId + " VARCHAR(200) NOT NULL UNIQUE, "
                    + checksum + " CHAR(64) NOT NULL, "
                    + description + " VARCHAR(500), "
                    + appliedBy + " VARCHAR(200), "
                    + appliedAt + " TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "
                    + executionMs + " BIGINT NOT NULL)";
            case SQLSERVER -> "IF OBJECT_ID(N'" + escapeLiteral(qualifiedHistory) + "', N'U') IS NULL "
                    + "CREATE TABLE " + qualifiedHistory + " ("
                    + installedRank + " BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY, "
                    + changeId + " VARCHAR(200) NOT NULL UNIQUE, "
                    + checksum + " CHAR(64) NOT NULL, "
                    + description + " VARCHAR(500) NULL, "
                    + appliedBy + " VARCHAR(200) NULL, "
                    + appliedAt + " DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(), "
                    + executionMs + " BIGINT NOT NULL)";
            case ORACLE -> "BEGIN EXECUTE IMMEDIATE '" + escapeLiteral("CREATE TABLE " + qualifiedHistory + " ("
                    + installedRank + " NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + changeId + " VARCHAR2(200) NOT NULL UNIQUE, "
                    + checksum + " CHAR(64) NOT NULL, "
                    + description + " VARCHAR2(500), "
                    + appliedBy + " VARCHAR2(200), "
                    + appliedAt + " TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL, "
                    + executionMs + " NUMBER NOT NULL)") + "'; "
                    + "EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;";
        };
    }

    /** Adds {@code applied_by} to an existing history table created by 1.2.0. */
    static String addAppliedByColumnDdl(DatabaseDialect dialect, String qualifiedHistory) {
        String appliedBy = SqlIdentifiers.quote(dialect, "applied_by");
        return switch (dialect) {
            case POSTGRESQL -> "ALTER TABLE " + qualifiedHistory
                    + " ADD COLUMN IF NOT EXISTS " + appliedBy + " VARCHAR(200)";
            // MariaDB accepts IF NOT EXISTS; MySQL 8/9 does not — catch duplicate column instead.
            case MARIADB -> "ALTER TABLE " + qualifiedHistory
                    + " ADD COLUMN IF NOT EXISTS " + appliedBy + " VARCHAR(200)";
            case MYSQL -> "ALTER TABLE " + qualifiedHistory
                    + " ADD COLUMN " + appliedBy + " VARCHAR(200)";
            // COL_LENGTH takes the column as a plain name, not a quoted identifier.
            case SQLSERVER -> "IF COL_LENGTH(N'" + escapeLiteral(qualifiedHistory)
                    + "', N'applied_by') IS NULL ALTER TABLE " + qualifiedHistory
                    + " ADD " + appliedBy + " VARCHAR(200) NULL";
            case ORACLE -> "BEGIN EXECUTE IMMEDIATE '" + escapeLiteral("ALTER TABLE " + qualifiedHistory
                    + " ADD " + appliedBy + " VARCHAR2(200)") + "'; "
                    + "EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;";
        };
    }

    /**
     * True when {@code error} is a duplicate-column failure for the dialect
     * (idempotent history {@code applied_by} migration).
     */
    static boolean isDuplicateColumn(DatabaseDialect dialect, SQLException error) {
        if (error == null) {
            return false;
        }
        for (Throwable current = error; current != null; current = nextSqlFailure(current)) {
            if (!(current instanceof SQLException sql)) {
                continue;
            }
            String state = sql.getSQLState();
            int code = sql.getErrorCode();
            switch (dialect) {
                case MYSQL, MARIADB -> {
                    // 1060 = ER_DUP_FIELDNAME
                    if (code == 1060 || "42S21".equals(state)) {
                        return true;
                    }
                }
                case POSTGRESQL -> {
                    // 42701 = duplicate_column
                    if ("42701".equals(state)) {
                        return true;
                    }
                }
                case SQLSERVER -> {
                    // 2705 = Column names in each table must be unique
                    if (code == 2705) {
                        return true;
                    }
                }
                case ORACLE -> {
                    // ORA-01430 = column being added already exists
                    if (code == 1430) {
                        return true;
                    }
                }
            }
        }
        return false;
    }

    /** Prefer {@link SQLException#getNextException()}, then {@link Throwable#getCause()}. */
    private static Throwable nextSqlFailure(Throwable current) {
        if (current instanceof SQLException sql && sql.getNextException() != null) {
            return sql.getNextException();
        }
        return current.getCause();
    }

    /**
     * The identity every dialect's synchronization lock is derived from: the namespace and the
     * history table, case-folded. Folding can only make two distinct ledgers share a lock (they then
     * run one after the other), never let two runs on the same ledger proceed together.
     */
    static String lockIdentity(String namespace, String historyTable) {
        return "schema_synchronizer:" + namespace.toLowerCase(Locale.ROOT) + "."
                + historyTable.toLowerCase(Locale.ROOT);
    }

    /** PostgreSQL two-key advisory lock for {@link #lockIdentity}. */
    static int[] postgresIdentityKeys(String namespace, String historyTable) {
        ByteBuffer digest = ByteBuffer.wrap(sha256(lockIdentity(namespace, historyTable)));
        return new int[]{digest.getInt(0), digest.getInt(4)};
    }

    /** MySQL/MariaDB GET_LOCK name for {@link #lockIdentity}; exactly 64 characters. */
    static String mysqlIdentityResource(String namespace, String historyTable) {
        return ("ss2_" + HexFormat.of().formatHex(sha256(lockIdentity(namespace, historyTable))))
                .substring(0, MYSQL_LOCK_NAME_MAX);
    }

    /** SQL Server sp_getapplock resource for {@link #lockIdentity}. */
    static String sqlServerIdentityResource(String namespace, String historyTable) {
        return "schema_synchronizer_v2_" + HexFormat.of().formatHex(sha256(lockIdentity(namespace, historyTable)));
    }

    /** Oracle DBMS_LOCK id for {@link #lockIdentity}. */
    static int oracleIdentityLockId(String namespace, String historyTable) {
        return Math.floorMod(ByteBuffer.wrap(sha256(lockIdentity(namespace, historyTable))).getInt(0),
                ORACLE_MAX_LOCK_ID);
    }

    private static final int ORACLE_MAX_LOCK_ID = 1_073_741_823;

    /**
     * Acquires the exclusive synchronization locks for {@code (namespace, historyTable)}, waiting
     * up to {@link #LOCK_WAIT_SECONDS} in total. Returns a token for {@link #releaseLock} ({@code null}
     * on PostgreSQL, whose locks are transaction-scoped). Every dialect also takes the lock the
     * previous releases took, in a fixed order after the new one, so a rolling upgrade still
     * excludes older peers; those older locks are what {@code advisoryLockId} still selects.
     *
     * @throws SchemaLockUnavailableException when another run holds a lock past the deadline
     */
    static String acquireLock(Connection conn, DatabaseDialect dialect, String namespace, String historyTable,
                              long advisoryLockId) throws SQLException {
        Objects.requireNonNull(namespace, "namespace");
        Objects.requireNonNull(historyTable, "historyTable");
        long deadline = System.nanoTime() + TimeUnit.SECONDS.toNanos(LOCK_WAIT_SECONDS);
        return switch (dialect) {
            case POSTGRESQL -> {
                int[] identity = postgresIdentityKeys(namespace, historyTable);
                // Pre-release 2.0 builds: namespace key paired with the configured id. 1.2.0: the configured id alone.
                int key1 = namespaceLockKey(namespace);
                int key2 = Math.floorMod(Long.hashCode(advisoryLockId), Integer.MAX_VALUE);
                acquirePostgresLocks(conn, deadline, List.of(
                        "SELECT pg_try_advisory_xact_lock(" + identity[0] + ", " + identity[1] + ")",
                        "SELECT pg_try_advisory_xact_lock(" + key1 + ", " + key2 + ")",
                        "SELECT pg_try_advisory_xact_lock(" + advisoryLockId + ")"));
                yield null;
            }
            case MARIADB, MYSQL -> {
                Set<String> resources = new LinkedHashSet<>();
                resources.add(mysqlIdentityResource(namespace, historyTable));
                resources.add(mysqlLockResource(namespace));
                resources.add(mysqlLockResourceLegacy(dialect, namespace));
                yield acquireAll(new ArrayList<>(resources),
                        resource -> {
                            acquireMysqlLock(conn, dialect, resource, deadline);
                            return true;
                        },
                        resource -> releaseMysqlLock(conn, resource));
            }
            case SQLSERVER -> acquireAll(List.of(
                            sqlServerIdentityResource(namespace, historyTable),
                            "schema_synchronizer_" + namespace.toLowerCase(Locale.ROOT)),
                    resource -> {
                        acquireSqlServerLock(conn, resource, deadline);
                        return true;
                    },
                    resource -> releaseSqlServerLock(conn, resource));
            case ORACLE -> {
                // release_on_commit=false: Oracle DDL implicitly commits; a transaction-
                // scoped lock would evaporate after the first CREATE/ALTER.
                Set<String> ids = new LinkedHashSet<>();
                ids.add(Integer.toString(oracleIdentityLockId(namespace, historyTable)));
                ids.add(Integer.toString(Math.floorMod(Objects.hash("schema_synchronizer",
                        namespace.toLowerCase(Locale.ROOT), advisoryLockId), ORACLE_MAX_LOCK_ID)));
                ids.add(Integer.toString(Math.floorMod(Long.hashCode(advisoryLockId), ORACLE_MAX_LOCK_ID)));
                // Only ids newly acquired here go into the token: status 4 means an outer
                // caller on this session already owns the lock and must keep it.
                yield acquireAll(new ArrayList<>(ids),
                        id -> requestOracleLock(conn, Integer.parseInt(id), deadline),
                        id -> releaseOracleLockId(conn, Integer.parseInt(id)));
            }
        };
    }

    @FunctionalInterface
    interface LockPartAcquire {
        /** @return whether this call newly acquired the part (and so must release it) */
        boolean acquire(String part) throws SQLException;
    }

    /**
     * Acquires {@code parts} in order. On failure, releases what this call acquired (failures
     * suppressed onto the original) and rethrows. Returns the owned parts joined by {@code :}.
     */
    static String acquireAll(List<String> parts, LockPartAcquire acquire, LockPartRelease release)
            throws SQLException {
        List<String> owned = new ArrayList<>();
        try {
            for (String part : parts) {
                if (acquire.acquire(part)) {
                    owned.add(part);
                }
            }
        } catch (RuntimeException | SQLException failure) {
            try {
                releaseEach(String.join(":", owned), release);
            } catch (RuntimeException | SQLException releaseFailure) {
                SchemaExceptions.suppress(failure, releaseFailure);
            }
            throw failure;
        }
        return String.join(":", owned);
    }

    /**
     * SQL Server and Oracle have no RELEASE SAVEPOINT (mssql-jdbc and ojdbc throw); their
     * savepoints end with the transaction.
     */
    static void releaseSavepoint(Connection conn, DatabaseDialect dialect, java.sql.Savepoint savepoint)
            throws SQLException {
        if (savepoint == null || dialect == DatabaseDialect.SQLSERVER || dialect == DatabaseDialect.ORACLE) {
            return;
        }
        conn.releaseSavepoint(savepoint);
    }

    /**
     * Releases every part of {@code lockToken}; a part the server reports as not held fails the
     * release (after the remaining parts are attempted).
     */
    static void releaseLock(Connection conn, DatabaseDialect dialect, String lockToken) throws SQLException {
        if (lockToken == null || lockToken.isBlank()) {
            return;
        }
        switch (dialect) {
            case MARIADB, MYSQL -> releaseEach(lockToken, part -> releaseMysqlLock(conn, part));
            case SQLSERVER -> releaseEach(lockToken, part -> releaseSqlServerLock(conn, part));
            case ORACLE -> releaseEach(lockToken, part -> releaseOracleLockId(conn, Integer.parseInt(part)));
            case POSTGRESQL -> {
                // transaction-scoped advisory lock released on commit/rollback
            }
        }
    }

    @FunctionalInterface
    interface LockPartRelease {
        void release(String part) throws SQLException;
    }

    /** Attempts every part so one failure cannot leave the other session lock held. */
    static void releaseEach(String lockToken, LockPartRelease release) throws SQLException {
        SQLException sqlFailure = null;
        RuntimeException runtimeFailure = null;
        for (String part : lockToken.split(":")) {
            if (part.isBlank()) {
                continue;
            }
            try {
                release.release(part);
            } catch (SQLException failure) {
                if (sqlFailure == null && runtimeFailure == null) {
                    sqlFailure = failure;
                } else {
                    SchemaExceptions.suppress(sqlFailure != null ? sqlFailure : runtimeFailure, failure);
                }
            } catch (RuntimeException failure) {
                if (sqlFailure == null && runtimeFailure == null) {
                    runtimeFailure = failure;
                } else {
                    SchemaExceptions.suppress(sqlFailure != null ? sqlFailure : runtimeFailure, failure);
                }
            }
        }
        if (sqlFailure != null) {
            throw sqlFailure;
        }
        if (runtimeFailure != null) {
            throw runtimeFailure;
        }
    }

    /** The lock name pre-release 2.0 builds used: SHA-256 form when over 64 characters. */
    static String mysqlLockResource(String namespace) {
        String full = "schema_synchronizer_" + namespace.toLowerCase(Locale.ROOT);
        if (full.length() <= MYSQL_LOCK_NAME_MAX) {
            return full;
        }
        // MySQL truncates GET_LOCK names at 64 chars — SHA-256 prefix avoids silent collisions.
        return ("ss_" + HexFormat.of().formatHex(sha256(full))).substring(0, MYSQL_LOCK_NAME_MAX);
    }

    /**
     * The lock name 1.2.0 used. It keeps the schema's case: MariaDB compares lock names
     * case-sensitively. MySQL rejects lock names over 64 characters, so 1.2.0 never held those
     * there; MariaDB accepts them.
     */
    static String mysqlLockResourceLegacy(DatabaseDialect dialect, String namespace) {
        String full = "schema_synchronizer_" + namespace;
        return dialect == DatabaseDialect.MARIADB || full.length() <= MYSQL_LOCK_NAME_MAX
                ? full : mysqlLockResource(namespace);
    }

    /** The PostgreSQL namespace key pre-release 2.0 builds used. */
    static int namespaceLockKey(String namespace) {
        return Math.floorMod(("schema_synchronizer_" + namespace.toLowerCase(Locale.ROOT)).hashCode(),
                Integer.MAX_VALUE);
    }

    private static byte[] sha256(String value) {
        try {
            return MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8));
        } catch (NoSuchAlgorithmException impossible) {
            // Every Java platform must provide SHA-256 (java.security.MessageDigest contract).
            throw new IllegalStateException("SHA-256 is unavailable", impossible);
        }
    }

    /** Whole seconds left before {@code deadline}, at least 0. */
    private static long remainingSeconds(long deadline) {
        long nanos = deadline - System.nanoTime();
        return nanos <= 0 ? 0 : Math.max(1, TimeUnit.NANOSECONDS.toSeconds(nanos));
    }

    private static SchemaLockUnavailableException lockTimeout(DatabaseDialect dialect, String detail) {
        return new SchemaLockUnavailableException("Could not acquire " + dialect.id()
                + " schema synchronization lock within " + LOCK_WAIT_SECONDS + "s" + detail
                + "; another synchronization of this schema is running");
    }

    private static void acquireMysqlLock(Connection conn, DatabaseDialect dialect, String resource, long deadline)
            throws SQLException {
        try (var statement = conn.prepareStatement("SELECT GET_LOCK(?, ?)")) {
            statement.setString(1, resource);
            statement.setLong(2, remainingSeconds(deadline));
            try (var row = statement.executeQuery()) {
                if (!row.next()) {
                    throw new SQLException("GET_LOCK returned no row");
                }
                int result = row.getInt(1);
                if (row.wasNull()) {
                    throw new SQLException("GET_LOCK('" + resource + "') returned NULL");
                }
                if (result != 1) {
                    throw lockTimeout(dialect, "");
                }
            }
        }
    }

    /** RELEASE_LOCK: 1 released, 0 held by another session, NULL no such lock. */
    private static void releaseMysqlLock(Connection conn, String resource) throws SQLException {
        try (var statement = conn.prepareStatement("SELECT RELEASE_LOCK(?)")) {
            statement.setString(1, resource);
            try (var row = statement.executeQuery()) {
                if (!row.next()) {
                    throw new SQLException("RELEASE_LOCK returned no row");
                }
                int result = row.getInt(1);
                if (row.wasNull()) {
                    throw new SQLException("RELEASE_LOCK('" + resource + "') found no such lock");
                }
                if (result != 1) {
                    throw new SQLException("RELEASE_LOCK('" + resource
                            + "') returned 0: the lock is not held by this session");
                }
            }
        }
    }

    /** sp_getapplock: 0/1 granted; -1 timeout, -2 canceled, -3 deadlock victim, -999 bad call. */
    private static void acquireSqlServerLock(Connection conn, String resource, long deadline) throws SQLException {
        try (var statement = conn.prepareStatement(
                "DECLARE @result INT; "
                        + "EXEC @result = sp_getapplock @Resource = ?, @LockMode = 'Exclusive', "
                        + "@LockOwner = 'Session', @LockTimeout = ?; "
                        + "SELECT @result")) {
            statement.setString(1, resource);
            statement.setLong(2, TimeUnit.SECONDS.toMillis(remainingSeconds(deadline)));
            try (var row = statement.executeQuery()) {
                if (!row.next()) {
                    throw new SQLException("sp_getapplock returned no row");
                }
                int result = row.getInt(1);
                if (result == -1 || result == -2 || result == -3) {
                    throw lockTimeout(DatabaseDialect.SQLSERVER, " (sp_getapplock=" + result + ")");
                }
                if (result < 0) {
                    throw new SQLException("sp_getapplock failed for '" + resource + "' (result=" + result + ")");
                }
            }
        }
    }

    private static void releaseSqlServerLock(Connection conn, String resource) throws SQLException {
        try (var statement = conn.prepareStatement(
                "DECLARE @result INT; "
                        + "EXEC @result = sp_releaseapplock @Resource = ?, @LockOwner = 'Session'; "
                        + "SELECT @result")) {
            statement.setString(1, resource);
            try (var row = statement.executeQuery()) {
                if (!row.next() || row.getInt(1) < 0) {
                    throw new SQLException("Could not release sqlserver schema synchronization lock '"
                            + resource + "'");
                }
            }
        }
    }

    private static final long LOCK_POLL_MILLIS = 100L;

    /**
     * Takes each lock in order. Strict order: never hold a later lock without the earlier ones,
     * so two synchronizers each holding a different part cannot wait on each other until the deadline.
     * pg_try_* with a deadline matches the other dialects' timeouts (pg_advisory_xact_lock waits forever).
     */
    private static void acquirePostgresLocks(Connection conn, long deadline, List<String> lockQueries)
            throws SQLException {
        int held = 0;
        try (Statement statement = conn.createStatement()) {
            while (held < lockQueries.size()) {
                if (tryPostgresLock(statement, lockQueries.get(held))) {
                    held++;
                    continue;
                }
                if (System.nanoTime() >= deadline) {
                    throw lockTimeout(DatabaseDialect.POSTGRESQL, "");
                }
                try {
                    Thread.sleep(LOCK_POLL_MILLIS);
                } catch (InterruptedException interrupted) {
                    Thread.currentThread().interrupt();
                    throw new SchemaLockUnavailableException(
                            "Interrupted while waiting for postgresql schema synchronization lock", interrupted);
                }
            }
        }
    }

    private static boolean tryPostgresLock(Statement statement, String sql) throws SQLException {
        try (var row = statement.executeQuery(sql)) {
            return row.next() && row.getBoolean(1);
        }
    }

    /**
     * DBMS_LOCK.REQUEST: 0 granted, 1 timeout, 2 deadlock, 3 parameter error, 4 already owned,
     * 5 illegal handle.
     *
     * @return true when newly acquired, false when this session already owned it (status 4)
     */
    private static boolean requestOracleLock(Connection conn, int lockId, long deadline) throws SQLException {
        try (var statement = conn.prepareCall("{ ? = call DBMS_LOCK.REQUEST(?, 6, ?, false) }")) {
            statement.registerOutParameter(1, Types.INTEGER);
            statement.setInt(2, lockId);
            statement.setLong(3, remainingSeconds(deadline));
            statement.execute();
            int status = statement.getInt(1);
            if (status == 0) {
                return true;
            }
            if (status == 4) {
                return false;
            }
            if (status == 1 || status == 2) {
                throw lockTimeout(DatabaseDialect.ORACLE, " (DBMS_LOCK status=" + status + ")");
            }
            throw new SQLException("DBMS_LOCK.REQUEST failed for lock " + lockId + " (status=" + status + ")");
        } catch (SQLException error) {
            if (isMissingDbmsLockGrant(error)) {
                String user = oracleUser(conn);
                throw new SchemaDatabaseException("Oracle user " + user
                        + " cannot execute SYS.DBMS_LOCK, which the schema synchronization lock needs; "
                        + "as a DBA run: GRANT EXECUTE ON DBMS_LOCK TO " + user, error);
            }
            throw error;
        }
    }

    /** ORA-06550 with PLS-00201 (identifier must be declared): DBMS_LOCK is not granted to the user. */
    static boolean isMissingDbmsLockGrant(SQLException error) {
        for (Throwable current = error; current != null; current = nextSqlFailure(current)) {
            String message = current.getMessage();
            if (message != null && message.contains("PLS-00201") && message.contains("DBMS_LOCK")) {
                return true;
            }
        }
        return false;
    }

    private static String oracleUser(Connection conn) {
        try {
            String user = conn.getMetaData().getUserName();
            return user == null || user.isBlank() ? "<user>" : user;
        } catch (SQLException | RuntimeException unavailable) {
            return "<user>";
        }
    }

    private static void releaseOracleLockId(Connection conn, int lockId) throws SQLException {
        try (var statement = conn.prepareCall("{ ? = call DBMS_LOCK.RELEASE(?) }")) {
            statement.registerOutParameter(1, Types.INTEGER);
            statement.setInt(2, lockId);
            statement.execute();
            int status = statement.getInt(1);
            // 0 = released; 3 = parameter error, 4 = not owned: the lock is not held by this session.
            if (status != 0) {
                throw new SQLException("Could not release oracle schema synchronization lock " + lockId
                        + " (status=" + status + ")");
            }
        }
    }

    private static String escapeLiteral(String value) {
        return value.replace("'", "''");
    }
}
