// Copyright 2026 ThinkAI LLC
// SPDX-License-Identifier: Apache-2.0

package com.thinkaillc.schemasynchronizer;

import java.util.Locale;
import java.util.regex.Pattern;

/**
 * JDBC metadata reports identity/serial columns as INT8/INT4 and drops
 * {@code nextval} from CREATE TABLE. SchemaSynchronizer then creates tables whose
 * {@code INSERT} leaves {@code id} null. Restore a sequence-backed type for
 * surrogate {@code id} primary keys only — never for FKs.
 *
 * <p>Repair invariants (existing tables):
 * <ul>
 *   <li>Attach IDENTITY and {@code setval} in one transaction.</li>
 *   <li>{@code LOCK TABLE ... SHARE ROW EXCLUSIVE} so concurrent INSERTs wait;
 *       {@code MAX(id)} cannot go stale under another replica.</li>
 *   <li>{@code setval(GREATEST(last_value, MAX(id)))} never rewinds a sequence
 *       that is already ahead of the table.</li>
 *   <li>Empty tables are not {@code setval}'d (identity already starts at 1).</li>
 *   <li>Only sole {@code PRIMARY KEY (id)} — not composite keys.</li>
 * </ul>
 */
final class PkIdentity {

    private static final Pattern SOLE_ID_PK = Pattern.compile("PRIMARY KEY \\(\"?ID\"?\\)", Pattern.CASE_INSENSITIVE);
    private static final Pattern SERIAL_ID = Pattern.compile("(?i)(?<![\\w\"])\"?id\"?\\s+(?:BIG)?SERIAL\\b");
    private static final String ID = SqlIdentifiers.quote(DatabaseDialect.POSTGRESQL, "id");

    /** The table as a PostgreSQL identifier: {@code "schema"."table"}, both exact catalog spellings. */
    private static String table(String schema, String table) {
        return SqlIdentifiers.quoteExact(DatabaseDialect.POSTGRESQL, schema) + "."
                + SqlIdentifiers.quoteExact(DatabaseDialect.POSTGRESQL, table);
    }

    /** {@code pg_get_serial_sequence} parses its first argument as SQL, so it gets the quoted name. */
    private static String serialSequence(String schema, String tableName) {
        return "pg_get_serial_sequence('" + table(schema, tableName).replace("'", "''") + "', 'id')";
    }

    static String lockTableSql(String schema, String tableName) {
        return "LOCK TABLE " + table(schema, tableName) + " IN SHARE ROW EXCLUSIVE MODE";
    }

    static String addGeneratedIdentitySql(String schema, String tableName) {
        return "ALTER TABLE " + table(schema, tableName) + " ALTER COLUMN " + ID + " ADD GENERATED BY DEFAULT AS IDENTITY";
    }

    /**
     * Advance the sequence to at least {@code MAX(id)}, never below {@code last_value}.
     * Empty table: third argument false so the next value stays 1.
     */
    static String syncIdentitySequenceSql(String schema, String tableName) {
        String t = table(schema, tableName);
        String seq = serialSequence(schema, tableName);
        return "SELECT setval(" + seq + ", "
                + "GREATEST("
                + "COALESCE((SELECT s.last_value FROM pg_sequences s "
                + "WHERE s.schemaname = n.nspname AND s.sequencename = c.relname), 1), "
                + "COALESCE((SELECT MAX(" + ID + ") FROM " + t + "), 1)"
                + "), "
                + "(SELECT MAX(" + ID + ") FROM " + t + ") IS NOT NULL) "
                + "FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace "
                + "WHERE c.oid = " + seq + "::regclass";
    }

    static boolean needsSequenceAdvance(Long seqLastValue, Long maxId) {
        if (maxId == null) {
            return false;
        }
        if (seqLastValue == null) {
            return true;
        }
        return seqLastValue <= maxId;
    }

    static String readSequenceStateSql(String schema, String tableName) {
        return "SELECT s.last_value, (SELECT MAX(" + ID + ") FROM " + table(schema, tableName) + ") AS max_id "
                + "FROM pg_sequences s JOIN pg_namespace n ON n.nspname = s.schemaname "
                + "JOIN pg_class c ON c.relnamespace = n.oid AND c.relname = s.sequencename "
                + "WHERE c.oid = " + serialSequence(schema, tableName) + "::regclass";
    }

    static boolean needsIdentityRepair(String attidentity, String serialSequence) {
        if (attidentity != null && !attidentity.isBlank()) {
            return false;
        }
        return serialSequence == null || serialSequence.isBlank();
    }

    static boolean hasSoleIdPrimaryKey(String createSql) {
        return createSql != null && SOLE_ID_PK.matcher(createSql).find();
    }

    static boolean createSqlWantsIdIdentity(String createSql) {
        if (!hasSoleIdPrimaryKey(createSql)) {
            return false;
        }
        String upper = createSql.toUpperCase(Locale.ROOT);
        return SERIAL_ID.matcher(createSql).find()
                || upper.contains("GENERATED BY DEFAULT AS IDENTITY")
                || upper.contains("GENERATED ALWAYS AS IDENTITY");
    }

    static String createType(String typeName, String nullable, String columnDefault,
                             boolean autoIncrement, boolean primaryKey) {
        if (isSequenceBackedInteger(typeName, columnDefault, autoIncrement)) {
            return serialKeyword(typeName) + nullable;
        }
        String base = switch (typeName) {
            case "BIGSERIAL", "SERIAL" -> typeName;
            case "INT2" -> "SMALLINT";
            default -> typeName;
        };
        base += nullable;
        if (columnDefault != null && !columnDefault.contains("nextval(")) {
            base += " DEFAULT " + columnDefault;
        }
        return base;
    }

    static boolean isSequenceBackedInteger(String typeName, String columnDefault, boolean autoIncrement) {
        if (!isIntegerFamily(typeName)) {
            return false;
        }
        return autoIncrement || (columnDefault != null && columnDefault.contains("nextval("));
    }

    static String restoreCreateSql(String createSql) {
        if (!hasSoleIdPrimaryKey(createSql)) {
            return createSql;
        }
        return createSql
                .replaceFirst("(?i)(?<![\\w\"])(\"?)id\\1 INT8 NOT NULL\\b", "$1id$1 BIGSERIAL NOT NULL")
                .replaceFirst("(?i)(?<![\\w\"])(\"?)id\\1 BIGINT NOT NULL\\b", "$1id$1 BIGSERIAL NOT NULL")
                .replaceFirst("(?i)(?<![\\w\"])(\"?)id\\1 INT4 NOT NULL\\b", "$1id$1 SERIAL NOT NULL")
                .replaceFirst("(?i)(?<![\\w\"])(\"?)id\\1 INTEGER NOT NULL\\b", "$1id$1 SERIAL NOT NULL");
    }

    static String restoreIdColumnDefinition(String columnName, String definition, String createSql) {
        if (definition == null || !"id".equalsIgnoreCase(columnName) || createSql == null) {
            return definition;
        }
        String sql = restoreCreateSql(createSql).toUpperCase(Locale.ROOT).replace("\"ID\"", "ID");
        String def = definition;
        if (sql.contains("ID BIGSERIAL NOT NULL") && def.toUpperCase(Locale.ROOT).startsWith("INT8 NOT NULL")) {
            return "BIGSERIAL" + def.substring("INT8".length());
        }
        if (sql.contains("ID BIGSERIAL NOT NULL") && def.toUpperCase(Locale.ROOT).startsWith("BIGINT NOT NULL")) {
            return "BIGSERIAL" + def.substring("BIGINT".length());
        }
        if (sql.contains("ID SERIAL NOT NULL") && def.toUpperCase(Locale.ROOT).startsWith("INT4 NOT NULL")) {
            return "SERIAL" + def.substring("INT4".length());
        }
        if (sql.contains("ID SERIAL NOT NULL") && def.toUpperCase(Locale.ROOT).startsWith("INTEGER NOT NULL")) {
            return "SERIAL" + def.substring("INTEGER".length());
        }
        return definition;
    }

    private static boolean isIntegerFamily(String typeName) {
        if (typeName == null) {
            return false;
        }
        String t = typeName.toUpperCase(Locale.ROOT);
        return "INT8".equals(t) || "BIGINT".equals(t) || "INT4".equals(t)
                || "INTEGER".equals(t) || "INT".equals(t);
    }

    private static String serialKeyword(String typeName) {
        String t = typeName.toUpperCase(Locale.ROOT);
        if ("INT4".equals(t) || "INTEGER".equals(t) || "INT".equals(t)) {
            return "SERIAL";
        }
        return "BIGSERIAL";
    }
}
