// Copyright 2026 ThinkAI LLC
// SPDX-License-Identifier: Apache-2.0

package com.thinkaillc.schemasynchronizer;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/** A ledger written by v1.2.0 (its table layout and checksum) is accepted and upgraded in place. */
@LiveDatabase(engine = "PostgreSQL (1.2.0 ledger)", properties = {
        "schema.test.jdbc.url",
        "schema.test.jdbc.user"})
class ChangeSetLedgerCompatibilityPostgresIntegrationTest {
    private final String schema = "ledger_v120_" + UUID.randomUUID().toString().replace("-", "");

    @AfterEach
    void dropSchema() throws Exception {
        LiveTestSupport.requireTestNamespace(schema, "schema");
        try (Connection connection = connection(); var statement = connection.createStatement()) {
            statement.execute("DROP SCHEMA IF EXISTS " + schema + " CASCADE");
        }
    }

    @Test
    void v120HistoryRowIsAcceptedAndTheLedgerGainsAppliedBy() throws Exception {
        try (Connection connection = connection(); var statement = connection.createStatement()) {
            statement.execute("CREATE SCHEMA " + schema);
            // Verbatim v1.2.0 ChangeSetExecutor.createHistory DDL for PostgreSQL.
            statement.execute("CREATE TABLE " + schema + ".schema_synchronizer_history ("
                    + "installed_rank BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "change_id VARCHAR(200) NOT NULL UNIQUE, "
                    + "checksum CHAR(64) NOT NULL, "
                    + "description VARCHAR(500), "
                    + "applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, "
                    + "execution_ms BIGINT NOT NULL)");
            statement.execute("CREATE TABLE " + schema + ".items (id BIGINT PRIMARY KEY)");
            statement.execute("INSERT INTO " + schema + ".schema_synchronizer_history "
                    + "(change_id, checksum, description, execution_ms) VALUES ('001-create', '"
                    + ChangeSetChecksumGoldenTest.CREATE_ITEMS_BEFORE + "', 'written by 1.2.0', 3)");
        }
        SchemaDefinition.ChangeSet applied = new SchemaDefinition.ChangeSet("001-create", "reworded description",
                List.of(ChangeSetChecksumGoldenTest.CREATE_ITEMS));
        SchemaDefinition.ChangeSet next = new SchemaDefinition.ChangeSet("002-note", "new in 2.0",
                List.of("ALTER TABLE items ADD COLUMN note TEXT"));

        try (Connection connection = connection()) {
            SchemaSynchronizationResult result = synchronizer()
                    .synchronizeWithResult(connection, new SchemaDefinition(Map.of(), List.of(applied, next)));
            assertThat(result.changeSetsApplied()).isEqualTo(1);
        }
        try (Connection connection = connection(); var statement = connection.createStatement();
             var rows = statement.executeQuery("SELECT change_id, checksum, applied_by FROM " + schema
                     + ".schema_synchronizer_history ORDER BY installed_rank")) {
            assertThat(rows.next()).isTrue();
            assertThat(rows.getString(1)).isEqualTo("001-create");
            assertThat(rows.getString(2)).isEqualTo(ChangeSetChecksumGoldenTest.CREATE_ITEMS_BEFORE);
            assertThat(rows.getString(3)).isNull();
            assertThat(rows.next()).isTrue();
            assertThat(rows.getString(1)).isEqualTo("002-note");
            assertThat(rows.getString(3)).isNotBlank();
            assertThat(rows.next()).isFalse();
        }

        SchemaDefinition.ChangeSet edited = new SchemaDefinition.ChangeSet("001-create", "d",
                List.of("CREATE TABLE items (id BIGINT PRIMARY KEY, extra INT)"));
        try (Connection connection = connection()) {
            assertThatThrownBy(() -> synchronizer().synchronizeWithResult(connection,
                    new SchemaDefinition(Map.of(), List.of(edited, next))))
                    .hasMessageContaining("checksum mismatch");
        }
    }

    private SchemaSynchronizer synchronizer() {
        return new SchemaSynchronizer(new ObjectMapper(), null, "",
                new SchemaSynchronizerOptions(schema, "schema_synchronizer_history", 7_249_031_147L,
                        false, true, true));
    }

    private static Connection connection() throws Exception {
        return DriverManager.getConnection(System.getProperty("schema.test.jdbc.url"),
                System.getProperty("schema.test.jdbc.user", ""), System.getProperty("schema.test.jdbc.password", ""));
    }
}
