// Copyright 2026 ThinkAI LLC
// SPDX-License-Identifier: Apache-2.0

package com.thinkaillc.schemasynchronizer;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Drives the real standalone entry points ({@code SchemaSerializer.main},
 * {@code SchemaSnapshotWriter.main} including {@code --restore-json}, and
 * {@code SchemaSynchronizer.main/dryRunMain/validateMain}) against live PostgreSQL. The
 * database password reaches them only through {@code SCHEMA_DB_PASSWORD}, so they run in a
 * child JVM.
 */
@LiveDatabase(engine = "PostgreSQL (CLI entry points)", properties = {
        "schema.test.jdbc.url",
        "schema.test.jdbc.user",
        "schema.test.jdbc.password"})
class CliEntryPointsPostgresIntegrationTest {
    private final List<String> cleanupSchemas = new ArrayList<>();
    private final ObjectMapper mapper = new ObjectMapper();

    @TempDir
    Path tempDirectory;

    @AfterEach
    void dropSchemas() throws Exception {
        try (Connection connection = connection(); var statement = connection.createStatement()) {
            for (String schema : cleanupSchemas) {
                LiveTestSupport.requireTestNamespace(schema, "schema");
                statement.execute("DROP SCHEMA IF EXISTS " + schema + " CASCADE");
            }
        }
    }

    @Test
    void serializeRestoreSyncAndReserializeRoundTrip() throws Exception {
        String source = createSchema("cli_source");
        String target = createSchema("cli_target");
        try (Connection connection = connection(); var statement = connection.createStatement()) {
            statement.execute("CREATE TABLE " + source + ".cli_items (id BIGINT GENERATED BY DEFAULT AS IDENTITY "
                    + "PRIMARY KEY, label VARCHAR(40) NOT NULL, note TEXT)");
            statement.execute("CREATE TABLE " + source + ".cli_links (id BIGSERIAL PRIMARY KEY, "
                    + "item_id BIGINT NOT NULL)");
            statement.execute("CREATE INDEX idx_cli_items_label ON " + source + ".cli_items (label)");
        }

        Path serialized = tempDirectory.resolve("serialized.json");
        cli("serialize", url(), user(), "-", source, serialized.toString()).assertSuccess();
        assertThat(serialized).isRegularFile();
        JsonNode original = mapper.readTree(serialized.toFile());
        assertThat(original.get("tables").fieldNames()).toIterable().containsExactlyInAnyOrder("cli_items", "cli_links");
        String itemsCreate = original.at("/tables/cli_items/createSql").asText();
        assertThat(itemsCreate).containsPattern("(?i)\\bid\\b[^,]*(BIGSERIAL|IDENTITY)");

        // A snapshot whose surrogate id lost its identity (as JDBC metadata reports it) is repaired
        // by --restore-json, and only for the sole-id primary key.
        Path stripped = tempDirectory.resolve("stripped.json");
        ObjectNode strippedRoot = (ObjectNode) mapper.readTree(serialized.toFile());
        for (String table : List.of("cli_items", "cli_links")) {
            ObjectNode node = (ObjectNode) strippedRoot.get("tables").get(table);
            node.put("createSql", node.get("createSql").asText()
                    .replaceAll("(?i)\\bBIGSERIAL\\b", "INT8"));
            for (JsonNode column : node.get("columns")) {
                ((ObjectNode) column).put("definition", column.get("definition").asText()
                        .replaceAll("(?i)\\bBIGSERIAL\\b", "INT8"));
            }
        }
        mapper.writeValue(stripped.toFile(), strippedRoot);
        assertThat(Files.readString(stripped)).doesNotContainIgnoringCase("BIGSERIAL");
        cli("snapshot", "--restore-json", stripped.toString()).assertSuccess();
        JsonNode restored = mapper.readTree(stripped.toFile());
        for (String table : List.of("cli_items", "cli_links")) {
            assertThat(restored.at("/tables/" + table + "/createSql").asText()).as(table)
                    .containsIgnoringCase("\"id\" BIGSERIAL");
        }
        assertThat(restored.at("/tables/cli_links/createSql").asText()).containsIgnoringCase("\"item_id\" INT8");

        cli("validate", stripped.toString(), target).assertSuccess();
        cli("sync", url(), user(), "-", stripped.toString(), target).assertSuccess();
        try (Connection connection = connection(); var statement = connection.createStatement()) {
            statement.execute("INSERT INTO " + target + ".cli_items (label) VALUES ('generated id')");
            statement.execute("INSERT INTO " + target + ".cli_links (item_id) VALUES (1)");
            try (var rows = statement.executeQuery("SELECT id FROM " + target + ".cli_items")) {
                assertThat(rows.next()).isTrue();
                assertThat(rows.getLong(1)).isEqualTo(1);
            }
            assertThat(count(connection, "SELECT count(*) FROM pg_indexes WHERE schemaname = '" + target
                    + "' AND indexname = 'idx_cli_items_label'")).isEqualTo(1);
        }

        Path reserialized = tempDirectory.resolve("reserialized.json");
        cli("serialize", url(), user(), "-", target, reserialized.toString()).assertSuccess();
        assertThat(mapper.readTree(reserialized.toFile()).get("tables")).isEqualTo(original.get("tables"));
    }

    @Test
    void dryRunPlansButChangesNothing() throws Exception {
        String target = createSchema("cli_dry_run");
        Path definition = writeDefinition();
        cli("sync", url(), user(), "-", definition.toString(), target).assertSuccess();
        String before = describe(target);

        ObjectNode root = (ObjectNode) mapper.readTree(definition.toFile());
        ((com.fasterxml.jackson.databind.node.ArrayNode) root.at("/tables/cli_orders/columns"))
                .addObject().put("name", "memo").put("definition", "VARCHAR(80)");
        ((com.fasterxml.jackson.databind.node.ArrayNode) root.at("/tables/cli_orders/indexes"))
                .add("CREATE INDEX IF NOT EXISTS idx_cli_orders_memo ON cli_orders (memo)");
        ((com.fasterxml.jackson.databind.node.ArrayNode) root.get("changes")).addObject()
                .put("id", "002-more").put("description", "second row").put("phase", "AFTER_SCHEMA")
                .putArray("statements").add("INSERT INTO cli_orders (status) VALUES ('dry')");
        Path widened = tempDirectory.resolve("widened.json");
        mapper.writeValue(widened.toFile(), root);

        cli("dry-run", url(), user(), "-", widened.toString(), target).assertSuccess();
        assertThat(describe(target)).isEqualTo(before);
        try (Connection connection = connection()) {
            assertThat(count(connection, "SELECT count(*) FROM " + target + ".schema_synchronizer_history"))
                    .isEqualTo(1);
            assertThat(count(connection, "SELECT count(*) FROM " + target + ".cli_orders")).isEqualTo(1);
        }
    }

    @Test
    void dryRunOfAFirstDeployChangesNothingAndSucceeds() throws Exception {
        String target = createSchema("cli_dry_first");
        cli("dry-run", url(), user(), "-", writeDefinition().toString(), target).assertSuccess();
        try (Connection connection = connection()) {
            assertThat(count(connection, "SELECT count(*) FROM information_schema.tables WHERE table_schema = '"
                    + target + "'")).as("tables after dry run").isZero();
        }
    }

    @Test
    void syncConvergesAndRecordsTheActor() throws Exception {
        String target = createSchema("cli_sync");
        Path definition = writeDefinition();
        Map<String, String> env = Map.of(CliCredentials.PASSWORD_ENV, password(),
                CliCredentials.ACTOR_ENV, "release-pipeline");
        ChildJvm.run(env, List.of(), "sync", url(), user(), "-", definition.toString(), target,
                "cli_history").assertSuccess();
        try (Connection connection = connection(); var statement = connection.createStatement()) {
            assertThat(count(connection, "SELECT count(*) FROM " + target + ".cli_history")).isEqualTo(1);
            try (var rows = statement.executeQuery("SELECT change_id, applied_by FROM " + target + ".cli_history")) {
                assertThat(rows.next()).isTrue();
                assertThat(rows.getString(1)).isEqualTo("001-seed");
                assertThat(rows.getString(2)).isEqualTo("release-pipeline");
            }
            assertThat(count(connection, "SELECT count(*) FROM " + target + ".cli_orders")).isEqualTo(1);
        }
        String before = describe(target);

        ChildJvm.run(env, List.of(), "sync", url(), user(), "-", definition.toString(), target,
                "cli_history").assertSuccess();
        assertThat(describe(target)).isEqualTo(before);
        try (Connection connection = connection()) {
            assertThat(count(connection, "SELECT count(*) FROM " + target + ".cli_history")).isEqualTo(1);
            assertThat(count(connection, "SELECT count(*) FROM " + target + ".cli_orders")).isEqualTo(1);
        }

        // Widening the definition adds exactly the new column on the next run.
        Path widened = tempDirectory.resolve("widened.json");
        ObjectNode root = (ObjectNode) mapper.readTree(definition.toFile());
        ((com.fasterxml.jackson.databind.node.ArrayNode) root.at("/tables/cli_orders/columns"))
                .addObject().put("name", "memo").put("definition", "VARCHAR(80)");
        mapper.writeValue(widened.toFile(), root);
        ChildJvm.run(env, List.of(), "sync", url(), user(), "-", widened.toString(), target,
                "cli_history").assertSuccess();
        try (Connection connection = connection()) {
            assertThat(count(connection, "SELECT count(*) FROM information_schema.columns WHERE table_schema = '"
                    + target + "' AND table_name = 'cli_orders' AND column_name = 'memo'")).isEqualTo(1);
        }
    }

    @Test
    void entryPointsRejectBadArgumentsBeforeConnecting() throws Exception {
        Path definition = writeDefinition();
        ChildJvm.Result literal = ChildJvm.run(Map.of(CliCredentials.PASSWORD_ENV, password()), List.of(),
                "sync", url(), user(), password(), definition.toString(), "public");
        assertThat(literal.exitCode()).isEqualTo(1);
        assertThat(literal.output()).contains("literal passwords on the command line are not allowed");

        ChildJvm.Result noEnv = ChildJvm.run(Map.of(), List.of(), "dry-run", url(), user(), "-",
                definition.toString());
        assertThat(noEnv.exitCode()).isEqualTo(1);
        assertThat(noEnv.output()).contains("SCHEMA_DB_PASSWORD must be set");

        ChildJvm.Result missingFile = cli("sync", url(), user(), "-",
                tempDirectory.resolve("absent.json").toString(), "public");
        assertThat(missingFile.exitCode()).isEqualTo(1);
        assertThat(missingFile.output()).contains("Schema definition does not exist");

        ChildJvm.Result usage = cli("sync", url(), user());
        assertThat(usage.exitCode()).isEqualTo(1);
        assertThat(usage.output()).contains("Usage: SchemaSynchronizer");

        ChildJvm.Result snapshotUsage = cli("serialize", url(), user(), "-");
        assertThat(snapshotUsage.exitCode()).isEqualTo(1);
        assertThat(snapshotUsage.output()).contains("Usage: SchemaSnapshotWriter");
    }

    @Test
    void validateRunsOfflineAndRejectsForbiddenChangeSets() throws Exception {
        Path definition = writeDefinition();
        // In-process with no database properties at all: validation never opens a connection.
        SchemaSynchronizer.validateMain(new String[]{definition.toString()});
        SchemaSynchronizer.validateMain(new String[]{definition.toString(), "some_schema"});

        Path forbidden = tempDirectory.resolve("forbidden.json");
        Files.writeString(forbidden, """
                {"formatVersion": 2, "dialect": "postgresql", "tables": {}, "changes": [
                  {"id": "001-drop", "description": "destructive", "statements": ["DROP TABLE cli_orders"]}
                ]}""");
        assertThatThrownBy(() -> SchemaSynchronizer.validateMain(new String[]{forbidden.toString()}))
                .hasMessageContaining("not allowed");
        assertThatThrownBy(() -> SchemaSynchronizer.validateMain(new String[]{}))
                .hasMessageContaining("Usage: SchemaSynchronizer validate");
        ChildJvm.Result child = ChildJvm.run(Map.of(), List.of(), "validate", definition.toString());
        child.assertSuccess();
    }

    private Path writeDefinition() throws Exception {
        Path definition = tempDirectory.resolve("definition-" + UUID.randomUUID() + ".json");
        Files.writeString(definition, """
                {"formatVersion": 2, "dialect": "postgresql",
                 "tables": {"cli_orders": {
                   "createSql": "CREATE TABLE IF NOT EXISTS cli_orders (id BIGSERIAL NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'new', PRIMARY KEY (id))",
                   "columns": [{"name": "id", "definition": "BIGSERIAL NOT NULL"},
                               {"name": "status", "definition": "VARCHAR(20) NOT NULL DEFAULT 'new'"}],
                   "indexes": ["CREATE INDEX IF NOT EXISTS idx_cli_orders_status ON cli_orders (status)"]}},
                 "changes": [{"id": "001-seed", "description": "seed row",
                   "statements": ["INSERT INTO cli_orders (status) VALUES ('seeded')"],
                   "phase": "AFTER_SCHEMA"}]}""");
        return definition;
    }

    private String describe(String schema) throws Exception {
        StringBuilder result = new StringBuilder();
        try (Connection connection = connection(); var statement = connection.createStatement();
             var rows = statement.executeQuery("SELECT table_name, column_name, data_type, is_nullable, "
                     + "column_default FROM information_schema.columns WHERE table_schema = '" + schema
                     + "' ORDER BY table_name, ordinal_position")) {
            while (rows.next()) {
                for (int i = 1; i <= 5; i++) {
                    result.append(rows.getString(i)).append(i == 5 ? "\n" : "|");
                }
            }
        }
        try (Connection connection = connection(); var statement = connection.createStatement();
             var rows = statement.executeQuery("SELECT indexname, indexdef FROM pg_indexes WHERE schemaname = '"
                     + schema + "' ORDER BY indexname")) {
            while (rows.next()) {
                result.append(rows.getString(1)).append('|').append(rows.getString(2)).append('\n');
            }
        }
        return result.toString();
    }

    private ChildJvm.Result cli(String... args) throws Exception {
        return ChildJvm.run(Map.of(CliCredentials.PASSWORD_ENV, password()), List.of(), args);
    }

    private String createSchema(String prefix) throws Exception {
        String schema = prefix + "_" + UUID.randomUUID().toString().replace("-", "");
        try (Connection connection = connection(); var statement = connection.createStatement()) {
            statement.execute("CREATE SCHEMA " + schema);
        }
        cleanupSchemas.add(schema);
        return schema;
    }

    private static long count(Connection connection, String sql) throws Exception {
        try (var statement = connection.createStatement(); var rows = statement.executeQuery(sql)) {
            rows.next();
            return rows.getLong(1);
        }
    }

    private static Connection connection() throws Exception {
        return DriverManager.getConnection(url(), user(), password());
    }

    private static String url() {
        return System.getProperty("schema.test.jdbc.url");
    }

    private static String user() {
        return System.getProperty("schema.test.jdbc.user");
    }

    private static String password() {
        return System.getProperty("schema.test.jdbc.password");
    }
}
