// Copyright 2026 ThinkAI LLC
// SPDX-License-Identifier: Apache-2.0

package com.thinkaillc.schemasynchronizer;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

class ColumnDefinitionParserTest {

    @Test
    void parsesVarcharNotNullWithDefault() {
        var spec = ColumnDefinitionParser.parse("VARCHAR(100) NOT NULL DEFAULT 'PENDING'");
        assertThat(spec.baseType()).isEqualTo("VARCHAR");
        assertThat(spec.length()).isEqualTo(100);
        assertThat(spec.notNull()).isTrue();
        assertThat(ColumnDefinitionParser.normalizeDefault(spec.defaultExpr()))
                .isEqualTo("'PENDING'");
    }

    @Test
    void stripsPostgresTypeCastOnDefault() {
        assertThat(ColumnDefinitionParser.normalizeDefault("'PENDING'::character varying"))
                .isEqualTo("'PENDING'");
        assertThat(ColumnDefinitionParser.normalizeDefault("false"))
                .isEqualTo("false");
    }

    @Test
    void parsesTextNullableNoDefault() {
        var spec = ColumnDefinitionParser.parse("TEXT");
        assertThat(spec.baseType()).isEqualTo("TEXT");
        assertThat(spec.length()).isNull();
        assertThat(spec.notNull()).isFalse();
        assertThat(spec.defaultExpr()).isNull();
    }

    @Test
    void parsesBigintDefault() {
        var spec = ColumnDefinitionParser.parse("BIGINT DEFAULT 0");
        assertThat(spec.baseType()).isEqualTo("BIGINT");
        assertThat(spec.notNull()).isFalse();
        assertThat(ColumnDefinitionParser.normalizeDefault(spec.defaultExpr())).isEqualTo("0");
    }

    @Test
    void parsesIdentityClausesWithoutTreatingThemAsDefaults() {
        var oracle = ColumnDefinitionParser.parse(
                "NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL");
        assertThat(oracle.baseType()).isEqualTo("NUMERIC");
        assertThat(oracle.notNull()).isTrue();
        assertThat(oracle.defaultExpr()).isNull();

        var sqlServer = ColumnDefinitionParser.parse("BIGINT NOT NULL IDENTITY(1,1)");
        assertThat(sqlServer.baseType()).isEqualTo("BIGINT");
        assertThat(sqlServer.notNull()).isTrue();
        assertThat(sqlServer.defaultExpr()).isNull();

        var bare = ColumnDefinitionParser.parse("BIGINT IDENTITY NOT NULL");
        assertThat(bare.baseType()).isEqualTo("BIGINT");
        assertThat(bare.notNull()).isTrue();
    }

    @Test
    void extractsNotNullWhenDefaultPrecedesIt() {
        var spec = ColumnDefinitionParser.parse("TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL");
        assertThat(spec.baseType()).isEqualTo("TIMESTAMP");
        assertThat(spec.notNull()).isTrue();
        assertThat(ColumnDefinitionParser.normalizeDefault(spec.defaultExpr()))
                .isEqualTo("CURRENT_TIMESTAMP");
    }

    @Test
    void preservesNotNullInsideQuotedDefaultExpressions() {
        var inside = ColumnDefinitionParser.parse("VARCHAR(50) DEFAULT 'is NOT NULL'");
        assertThat(inside.notNull()).isFalse();
        assertThat(ColumnDefinitionParser.normalizeDefault(inside.defaultExpr()))
                .isEqualTo("'is NOT NULL'");

        var mixed = ColumnDefinitionParser.parse("VARCHAR(50) DEFAULT 'x NOT NULL y'");
        assertThat(mixed.notNull()).isFalse();
        assertThat(ColumnDefinitionParser.normalizeDefault(mixed.defaultExpr()))
                .isEqualTo("'x NOT NULL y'");

        var both = ColumnDefinitionParser.parse("VARCHAR(50) NOT NULL DEFAULT 'is NOT NULL'");
        assertThat(both.notNull()).isTrue();
        assertThat(ColumnDefinitionParser.normalizeDefault(both.defaultExpr()))
                .isEqualTo("'is NOT NULL'");

        var afterLiteral = ColumnDefinitionParser.parse("VARCHAR(50) DEFAULT 'is' NOT NULL");
        assertThat(afterLiteral.notNull()).isTrue();
        assertThat(ColumnDefinitionParser.normalizeDefault(afterLiteral.defaultExpr()))
                .isEqualTo("'is'");
    }

    @Test
    void parsesOracleTimestampWithTimeZoneForms() {
        var tstz = ColumnDefinitionParser.parse("TIMESTAMP(6) WITH TIME ZONE NOT NULL");
        assertThat(tstz.baseType()).isEqualTo("TIMESTAMPTZ");
        assertThat(tstz.notNull()).isTrue();

        var local = ColumnDefinitionParser.parse("TIMESTAMP WITH LOCAL TIME ZONE");
        assertThat(local.baseType()).isEqualTo("TIMESTAMPTZ");
        assertThat(local.notNull()).isFalse();
    }

    @Test
    void parsesSqlServerMaxLengthTypes() {
        var varchar = ColumnDefinitionParser.parse("VARCHAR(MAX) NOT NULL");
        assertThat(varchar.baseType()).isEqualTo("VARCHAR");
        assertThat(varchar.length()).isEqualTo(ColumnDefinitionParser.MAX_LENGTH);
        assertThat(varchar.notNull()).isTrue();

        var nvarchar = ColumnDefinitionParser.parse("NVARCHAR(MAX)");
        assertThat(nvarchar.baseType()).isEqualTo("VARCHAR");
        assertThat(nvarchar.length()).isEqualTo(ColumnDefinitionParser.MAX_LENGTH);

        var varbinary = ColumnDefinitionParser.parse("VARBINARY(MAX)");
        assertThat(varbinary.baseType()).isEqualTo("VARBINARY");
        assertThat(varbinary.length()).isEqualTo(ColumnDefinitionParser.MAX_LENGTH);

        assertThat(NonDestructiveAlterPlanner.formatType("VARCHAR", ColumnDefinitionParser.MAX_LENGTH, null))
                .isEqualTo("VARCHAR(MAX)");
        assertThat(NonDestructiveAlterPlanner.formatType("VARBINARY", ColumnDefinitionParser.MAX_LENGTH, null))
                .isEqualTo("VARBINARY(MAX)");
        assertThat(NonDestructiveAlterPlanner.classifyTypeChange(
                "VARCHAR", 100, null, "VARCHAR", ColumnDefinitionParser.MAX_LENGTH, null))
                .isEqualTo(NonDestructiveAlterPlanner.TypeChange.WIDEN);
    }

    @Test
    void rejectsCharMax() {
        org.assertj.core.api.Assertions.assertThatThrownBy(
                        () -> ColumnDefinitionParser.parse("CHAR(MAX)"))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("VARCHAR/VARBINARY");
    }
}
