// Copyright 2026 ThinkAI LLC
// SPDX-License-Identifier: Apache-2.0

package com.thinkaillc.schemasynchronizer;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

class ColumnDefinitionParserTest {

    @Test
    void parsesVarcharNotNullWithDefault() {
        var spec = ColumnDefinitionParser.parse("VARCHAR(100) NOT NULL DEFAULT 'PENDING'");
        assertThat(spec.baseType()).isEqualTo("VARCHAR");
        assertThat(spec.length()).isEqualTo(100);
        assertThat(spec.notNull()).isTrue();
        assertThat(ColumnDefinitionParser.normalizeDefault(spec.defaultExpr()))
                .isEqualTo("'PENDING'");
    }

    @Test
    void stripsPostgresTypeCastOnDefault() {
        assertThat(ColumnDefinitionParser.normalizeDefault("'PENDING'::character varying"))
                .isEqualTo("'PENDING'");
        assertThat(ColumnDefinitionParser.normalizeDefault("false"))
                .isEqualTo("false");
    }

    @Test
    void parsesTextNullableNoDefault() {
        var spec = ColumnDefinitionParser.parse("TEXT");
        assertThat(spec.baseType()).isEqualTo("TEXT");
        assertThat(spec.length()).isNull();
        assertThat(spec.notNull()).isFalse();
        assertThat(spec.defaultExpr()).isNull();
    }

    @Test
    void parsesBigintDefault() {
        var spec = ColumnDefinitionParser.parse("BIGINT DEFAULT 0");
        assertThat(spec.baseType()).isEqualTo("BIGINT");
        assertThat(spec.notNull()).isFalse();
        assertThat(ColumnDefinitionParser.normalizeDefault(spec.defaultExpr())).isEqualTo("0");
    }

    @Test
    void parsesIdentityClausesWithoutTreatingThemAsDefaults() {
        var oracle = ColumnDefinitionParser.parse(
                "NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL");
        assertThat(oracle.baseType()).isEqualTo("NUMERIC");
        assertThat(oracle.notNull()).isTrue();
        assertThat(oracle.defaultExpr()).isNull();

        var sqlServer = ColumnDefinitionParser.parse("BIGINT NOT NULL IDENTITY(1,1)");
        assertThat(sqlServer.baseType()).isEqualTo("BIGINT");
        assertThat(sqlServer.notNull()).isTrue();
        assertThat(sqlServer.defaultExpr()).isNull();

        var bare = ColumnDefinitionParser.parse("BIGINT IDENTITY NOT NULL");
        assertThat(bare.baseType()).isEqualTo("BIGINT");
        assertThat(bare.notNull()).isTrue();
    }
}
