// Copyright 2026 ThinkAI LLC
// SPDX-License-Identifier: Apache-2.0

package com.thinkaillc.schemasynchronizer;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

@EnabledIfSystemProperty(named = "schema.test.oracle.jdbc.url", matches = ".+")
class SchemaSynchronizerOracleIntegrationTest {

    @BeforeEach
    @AfterEach
    void cleanDatabase() throws Exception {
        try (Connection connection = connection(); var statement = connection.createStatement()) {
            dropIfExists(statement, "oracle_items");
            dropIfExists(statement, "oracle_strict");
            dropIfExists(statement, "oraclexitems");
            dropIfExists(statement, "schema_synchronizer_history");
        }
    }

    @Test
    void tableNamesAreNotMetadataPatterns() throws Exception {
        try (Connection connection = connection(); var statement = connection.createStatement()) {
            statement.execute("CREATE TABLE oracle_items (id NUMBER(10) NOT NULL, PRIMARY KEY (id))");
            // `_` is a metadata wildcard: this table must not lend its columns to oracle_items.
            statement.execute("CREATE TABLE oraclexitems (id NUMBER(10) NOT NULL, extra NUMBER(10), PRIMARY KEY (id))");
        }
        List<SchemaDefinition.ColumnDef> columns = List.of(new SchemaDefinition.ColumnDef("id", "NUMBER(10) NOT NULL"),
                new SchemaDefinition.ColumnDef("extra", "NUMBER(10)"));
        SchemaDefinition declared = new SchemaDefinition(2, "oracle", Map.of(
                "oracle_items", new SchemaDefinition.TableDef(
                        "CREATE TABLE oracle_items (id NUMBER(10) NOT NULL, PRIMARY KEY (id))", columns, List.of()),
                "oraclexitems", new SchemaDefinition.TableDef(
                        "CREATE TABLE oraclexitems (id NUMBER(10) NOT NULL, extra NUMBER(10), PRIMARY KEY (id))",
                        columns, List.of())), List.of());
        try (Connection connection = connection()) {
            SchemaSynchronizationResult result = synchronizer(true).synchronizeWithResult(connection, declared);
            assertThat(result.columnsAdded()).isEqualTo(1);
            assertThat(result.pendingSql()).isEmpty();
        }
        try (Connection connection = connection()) {
            assertThat(synchronizer(true).synchronizeWithResult(connection, declared).changed()).isFalse();
        }

        // A bare DEC is NUMBER(38,0): it matches that column and never rounds a wider-scale one.
        try (Connection connection = connection(); var statement = connection.createStatement()) {
            statement.execute("ALTER TABLE oracle_items ADD (plain NUMBER(38,0), wide NUMBER(20,4))");
            statement.execute("INSERT INTO oracle_items (id, wide) VALUES (1, 1.2345)");
        }
        List<SchemaDefinition.ColumnDef> numeric = new java.util.ArrayList<>(columns);
        numeric.add(new SchemaDefinition.ColumnDef("plain", "DEC"));
        numeric.add(new SchemaDefinition.ColumnDef("wide", "DEC"));
        SchemaDefinition bare = new SchemaDefinition(2, "oracle", Map.of(
                "oracle_items", new SchemaDefinition.TableDef(
                        "CREATE TABLE oracle_items (id NUMBER(10) NOT NULL, PRIMARY KEY (id))", numeric, List.of()),
                "oraclexitems", declared.tables().get("oraclexitems")), List.of());
        try (Connection connection = connection()) {
            SchemaSynchronizationResult result = synchronizer(false).synchronizeWithResult(connection, bare);
            assertThat(result.columnsAltered()).isZero();
            assertThat(result.pendingSql()).singleElement().asString().contains("wide");
        }
        try (Connection connection = connection(); var statement = connection.createStatement();
             var rows = statement.executeQuery("SELECT wide FROM oracle_items WHERE id = 1")) {
            assertThat(rows.next()).isTrue();
            assertThat(rows.getBigDecimal(1)).isEqualByComparingTo("1.2345");
        }
    }

    @Test
    void createsSerializesReplaysWidensIndexesAndReportsDestructiveDrift(@TempDir Path tempDir) throws Exception {
        SchemaSynchronizer synchronizer = synchronizer();
        SchemaDefinition initial = definition(List.of(
                new SchemaDefinition.ColumnDef("id", "NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL"),
                new SchemaDefinition.ColumnDef("label", "VARCHAR2(40) NOT NULL")));

        try (Connection connection = connection()) {
            assertThat(DatabaseDialect.detect(connection.getMetaData())).isEqualTo(DatabaseDialect.ORACLE);
            SchemaSynchronizationResult first = synchronizer.synchronizeWithResult(connection, initial);
            assertThat(first.tablesCreated()).isEqualTo(1);
        }
        try (Connection connection = connection()) {
            assertThat(synchronizer.synchronizeWithResult(connection, initial).changed()).isFalse();
        }

        SchemaDefinition additive = definition(List.of(
                new SchemaDefinition.ColumnDef("id", "NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL"),
                new SchemaDefinition.ColumnDef("label", "VARCHAR2(100) NOT NULL"),
                new SchemaDefinition.ColumnDef("notes", "VARCHAR2(255)")));
        try (Connection connection = connection()) {
            SchemaSynchronizationResult changed = synchronizer.synchronizeWithResult(connection, additive);
            assertThat(changed.columnsAdded()).isEqualTo(1);
            assertThat(changed.columnsAltered()).isEqualTo(1);
        }
        try (Connection connection = connection()) {
            assertThat(synchronizer.synchronizeWithResult(connection, additive).changed()).isFalse();
        }

        Path snapshot = tempDir.resolve("schema-definition.json");
        try (Connection connection = connection()) {
            SchemaSnapshotWriter.writeSnapshot(connection, schema(), snapshot);
        }
        SchemaDefinition serialized = new ObjectMapper().readValue(snapshot.toFile(), SchemaDefinition.class);
        assertThat(serialized.declaredDialect()).isEqualTo(DatabaseDialect.ORACLE);
        assertThat(serialized.tables()).containsKey("oracle_items");

        try (Connection connection = connection()) {
            assertThat(synchronizer.synchronizeWithResult(connection, initial).pendingSql())
                    .anyMatch(sql -> sql.toLowerCase(Locale.ROOT).contains("drop column notes"));
        }
    }

    @Test
    void strictResyncAndSnapshotReplayHaveNoPendingDrift(@TempDir Path tempDir) throws Exception {
        String create = "CREATE TABLE oracle_strict (id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "
                + "code INTEGER NOT NULL, label VARCHAR2(40) DEFAULT 'new' NOT NULL, "
                + "qty NUMBER(10,2) DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, "
                + "national_name NVARCHAR2(50), amount NUMBER, total NUMERIC, ratio DOUBLE PRECISION, "
                + "flag CHAR(1), token RAW(16), zoned TIMESTAMP(3) WITH TIME ZONE, "
                + "local_ts TIMESTAMP WITH LOCAL TIME ZONE, coarse TIMESTAMP(0), PRIMARY KEY (id))";
        List<String> indexes = List.of(
                "CREATE INDEX idx_oracle_strict_label ON oracle_strict (label, code)",
                "CREATE UNIQUE INDEX idx_oracle_strict_code ON oracle_strict (code);");
        SchemaDefinition initial = strictDefinition(create, List.of(
                new SchemaDefinition.ColumnDef("id", "NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL"),
                new SchemaDefinition.ColumnDef("code", "INTEGER NOT NULL"),
                new SchemaDefinition.ColumnDef("label", "VARCHAR2(40) DEFAULT 'new' NOT NULL"),
                new SchemaDefinition.ColumnDef("qty", "NUMBER(10,2) DEFAULT 0"),
                new SchemaDefinition.ColumnDef("created_at", "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"),
                new SchemaDefinition.ColumnDef("national_name", "NVARCHAR2(50)"),
                new SchemaDefinition.ColumnDef("amount", "NUMBER"),
                new SchemaDefinition.ColumnDef("total", "NUMERIC"),
                new SchemaDefinition.ColumnDef("ratio", "DOUBLE PRECISION"),
                new SchemaDefinition.ColumnDef("flag", "CHAR(1)"),
                new SchemaDefinition.ColumnDef("token", "RAW(16)"),
                new SchemaDefinition.ColumnDef("zoned", "TIMESTAMP(3) WITH TIME ZONE"),
                new SchemaDefinition.ColumnDef("local_ts", "TIMESTAMP WITH LOCAL TIME ZONE"),
                new SchemaDefinition.ColumnDef("coarse", "TIMESTAMP(0)")), indexes);

        try (Connection connection = connection()) {
            assertThat(synchronizer(true).synchronizeWithResult(connection, initial).tablesCreated()).isEqualTo(1);
            try (var statement = connection.createStatement()) {
                // Live-only function-based index: omitted from reconstruction, never reported as drift.
                statement.execute("CREATE INDEX idx_oracle_strict_desc ON oracle_strict (created_at DESC)");
            }
        }
        try (Connection connection = connection()) {
            SchemaSynchronizationResult strict = synchronizer(true).synchronizeWithResult(connection, initial);
            assertThat(strict.pendingSql()).isEmpty();
            assertThat(strict.changed()).isFalse();
        }

        SchemaDefinition relaxed = strictDefinition(create, List.of(
                new SchemaDefinition.ColumnDef("id", "NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL"),
                new SchemaDefinition.ColumnDef("code", "INTEGER"),
                new SchemaDefinition.ColumnDef("label", "VARCHAR2(100) DEFAULT 'new' NOT NULL"),
                new SchemaDefinition.ColumnDef("qty", "NUMBER(10,2) DEFAULT 1"),
                new SchemaDefinition.ColumnDef("created_at", "TIMESTAMP"),
                new SchemaDefinition.ColumnDef("national_name", "NVARCHAR2(50)"),
                new SchemaDefinition.ColumnDef("amount", "NUMBER"),
                new SchemaDefinition.ColumnDef("total", "NUMERIC"),
                new SchemaDefinition.ColumnDef("ratio", "DOUBLE PRECISION"),
                new SchemaDefinition.ColumnDef("flag", "CHAR(1)"),
                new SchemaDefinition.ColumnDef("token", "RAW(16)"),
                new SchemaDefinition.ColumnDef("zoned", "TIMESTAMP(3) WITH TIME ZONE"),
                new SchemaDefinition.ColumnDef("local_ts", "TIMESTAMP WITH LOCAL TIME ZONE"),
                new SchemaDefinition.ColumnDef("coarse", "TIMESTAMP(0)")), indexes);
        try (Connection connection = connection()) {
            SchemaSynchronizationResult altered = synchronizer(true).synchronizeWithResult(connection, relaxed);
            assertThat(altered.pendingSql()).isEmpty();
            assertThat(altered.columnsAltered()).isEqualTo(4);
        }
        try (Connection connection = connection()) {
            assertThat(synchronizer(true).synchronizeWithResult(connection, relaxed).changed()).isFalse();
        }

        List<SchemaDefinition.ColumnDef> finer = relaxed.tables().get("oracle_strict").columns().stream()
                .map(column -> switch (column.name()) {
                    case "zoned" -> new SchemaDefinition.ColumnDef("zoned", "TIMESTAMP(6) WITH TIME ZONE");
                    case "local_ts" -> new SchemaDefinition.ColumnDef("local_ts", "TIMESTAMP WITH TIME ZONE");
                    default -> column;
                })
                .toList();
        try (Connection connection = connection()) {
            SchemaSynchronizationResult drift = synchronizer(false)
                    .synchronizeWithResult(connection, strictDefinition(create, finer, indexes));
            assertThat(drift.columnsAltered()).isZero();
            assertThat(drift.pendingSql())
                    .anyMatch(sql -> sql.contains("MODIFY (zoned TIMESTAMP(6) WITH TIME ZONE"))
                    .anyMatch(sql -> sql.contains("MODIFY (local_ts TIMESTAMP WITH TIME ZONE"));
        }

        Path snapshot = tempDir.resolve("schema-definition.json");
        try (Connection connection = connection()) {
            SchemaSnapshotWriter.writeSnapshot(connection, schema(), snapshot);
        }
        SchemaDefinition serialized = new ObjectMapper().readValue(snapshot.toFile(), SchemaDefinition.class);
        assertThat(serialized.tables().get("oracle_strict").indexes())
                .noneMatch(sql -> sql.contains("idx_oracle_strict_desc"));
        try (Connection connection = connection(); var statement = connection.createStatement()) {
            dropIfExists(statement, "oracle_strict");
        }
        try (Connection connection = connection()) {
            assertThat(synchronizer(true).synchronizeWithResult(connection, serialized).tablesCreated()).isEqualTo(1);
        }
        try (Connection connection = connection()) {
            SchemaSynchronizationResult replayed = synchronizer(true).synchronizeWithResult(connection, serialized);
            assertThat(replayed.pendingSql()).isEmpty();
            assertThat(replayed.changed()).isFalse();
        }
    }

    @Test
    void floatBinaryPrecisionAndLocalTimeZonePrecisionAreCompared(@TempDir Path tempDir) throws Exception {
        String create = "CREATE TABLE oracle_strict (id NUMBER(10) NOT NULL, single_col REAL, double_col FLOAT, "
                + "narrow FLOAT(10), widen REAL, local_ts TIMESTAMP WITH LOCAL TIME ZONE, "
                + "local_ms TIMESTAMP(3) WITH LOCAL TIME ZONE, PRIMARY KEY (id))";
        List<SchemaDefinition.ColumnDef> matching = List.of(
                new SchemaDefinition.ColumnDef("id", "NUMBER(10) NOT NULL"),
                new SchemaDefinition.ColumnDef("single_col", "REAL"),
                new SchemaDefinition.ColumnDef("double_col", "DOUBLE PRECISION"),
                new SchemaDefinition.ColumnDef("narrow", "FLOAT(10)"),
                new SchemaDefinition.ColumnDef("widen", "FLOAT(63)"),
                new SchemaDefinition.ColumnDef("local_ts", "TIMESTAMP(6) WITH LOCAL TIME ZONE"),
                new SchemaDefinition.ColumnDef("local_ms", "TIMESTAMP(3) WITH LOCAL TIME ZONE"));
        try (Connection connection = connection()) {
            assertThat(synchronizer(true).synchronizeWithResult(connection,
                    strictDefinition(create, matching, List.of())).tablesCreated()).isEqualTo(1);
        }
        try (Connection connection = connection()) {
            SchemaSynchronizationResult strict = synchronizer(true)
                    .synchronizeWithResult(connection, strictDefinition(create, matching, List.of()));
            assertThat(strict.pendingSql()).isEmpty();
            assertThat(strict.changed()).isFalse();
        }

        List<SchemaDefinition.ColumnDef> drifted = List.of(
                new SchemaDefinition.ColumnDef("id", "NUMBER(10) NOT NULL"),
                new SchemaDefinition.ColumnDef("single_col", "FLOAT"),
                new SchemaDefinition.ColumnDef("double_col", "REAL"),
                new SchemaDefinition.ColumnDef("narrow", "FLOAT(126)"),
                new SchemaDefinition.ColumnDef("widen", "DOUBLE PRECISION"),
                new SchemaDefinition.ColumnDef("local_ts", "TIMESTAMP(3) WITH LOCAL TIME ZONE"),
                new SchemaDefinition.ColumnDef("local_ms", "TIMESTAMP WITH LOCAL TIME ZONE"));
        try (Connection connection = connection()) {
            SchemaSynchronizationResult result = synchronizer(false)
                    .synchronizeWithResult(connection, strictDefinition(create, drifted, List.of()));
            // A higher binary precision keeps every stored value; a lower one or any temporal change does not.
            assertThat(result.columnsAltered()).isEqualTo(3);
            assertThat(result.pendingSql()).hasSize(3)
                    .anyMatch(sql -> sql.contains("MODIFY (double_col REAL)"))
                    .anyMatch(sql -> sql.contains("MODIFY (local_ts TIMESTAMP(3) WITH LOCAL TIME ZONE)"))
                    .anyMatch(sql -> sql.contains("MODIFY (local_ms TIMESTAMP WITH LOCAL TIME ZONE)"));
        }
        try (Connection connection = connection(); var statement = connection.createStatement();
             var rows = statement.executeQuery("SELECT column_name, data_precision FROM user_tab_columns "
                     + "WHERE table_name = 'ORACLE_STRICT' AND data_type = 'FLOAT'")) {
            Map<String, Integer> precisions = new java.util.HashMap<>();
            while (rows.next()) {
                precisions.put(rows.getString(1).toLowerCase(Locale.ROOT), rows.getInt(2));
            }
            assertThat(precisions).containsEntry("single_col", 126).containsEntry("double_col", 126)
                    .containsEntry("narrow", 126).containsEntry("widen", 126);
        }

        try (Connection connection = connection(); var statement = connection.createStatement()) {
            dropIfExists(statement, "oracle_strict");
        }
        try (Connection connection = connection()) {
            synchronizer(true).synchronizeWithResult(connection, strictDefinition(create, matching, List.of()));
        }
        Path snapshot = tempDir.resolve("schema-definition.json");
        try (Connection connection = connection()) {
            SchemaSnapshotWriter.writeSnapshot(connection, schema(), snapshot);
        }
        SchemaDefinition serialized = new ObjectMapper().readValue(snapshot.toFile(), SchemaDefinition.class);
        assertThat(serialized.tables().get("oracle_strict").columns())
                .extracting(SchemaDefinition.ColumnDef::definition)
                .contains("FLOAT(63)", "FLOAT", "FLOAT(10)", "TIMESTAMP(6) WITH LOCAL TIME ZONE",
                        "TIMESTAMP(3) WITH LOCAL TIME ZONE");
        try (Connection connection = connection(); var statement = connection.createStatement()) {
            dropIfExists(statement, "oracle_strict");
        }
        try (Connection connection = connection()) {
            assertThat(synchronizer(true).synchronizeWithResult(connection, serialized).tablesCreated()).isEqualTo(1);
        }
        try (Connection connection = connection()) {
            SchemaSynchronizationResult replayed = synchronizer(true).synchronizeWithResult(connection, serialized);
            assertThat(replayed.pendingSql()).isEmpty();
            assertThat(replayed.changed()).isFalse();
        }
    }

    private SchemaDefinition strictDefinition(String create, List<SchemaDefinition.ColumnDef> columns,
                                              List<String> indexes) {
        return new SchemaDefinition(2, "oracle", Map.of("oracle_strict",
                new SchemaDefinition.TableDef(create, columns, indexes)), List.of());
    }

    private void dropIfExists(java.sql.Statement statement, String table) throws Exception {
        try {
            statement.execute("DROP TABLE " + table + " PURGE");
        } catch (Exception ignored) {
            // table may not exist
        }
    }

    private SchemaDefinition definition(List<SchemaDefinition.ColumnDef> columns) {
        return new SchemaDefinition(2, "oracle", Map.of("oracle_items",
                new SchemaDefinition.TableDef(
                        "CREATE TABLE oracle_items (id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "
                                + "label VARCHAR2(40) NOT NULL, PRIMARY KEY (id))",
                        columns,
                        List.of("CREATE INDEX idx_oracle_items_label ON oracle_items (label)"))),
                List.of());
    }

    private SchemaSynchronizer synchronizer() {
        return synchronizer(false);
    }

    private SchemaSynchronizer synchronizer(boolean failOnPending) {
        return new SchemaSynchronizer(new ObjectMapper(), null, "",
                new SchemaSynchronizerOptions(schema(), "schema_synchronizer_history", 7_249_031_147L,
                        false, failOnPending, true));
    }

    private String schema() {
        String configured = System.getProperty("schema.test.oracle.jdbc.schema");
        if (configured != null && !configured.isBlank()) {
            return configured.toLowerCase(Locale.ROOT);
        }
        return System.getProperty("schema.test.oracle.jdbc.user").toLowerCase(Locale.ROOT);
    }

    private Connection connection() throws Exception {
        return DriverManager.getConnection(
                System.getProperty("schema.test.oracle.jdbc.url"),
                System.getProperty("schema.test.oracle.jdbc.user"),
                System.getProperty("schema.test.oracle.jdbc.password"));
    }
}
