// Copyright 2026 ThinkAI LLC
// SPDX-License-Identifier: Apache-2.0

package com.thinkaillc.schemasynchronizer;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

@EnabledIfSystemProperty(named = "schema.test.oracle.jdbc.url", matches = ".+")
class SchemaSynchronizerOracleIntegrationTest {

    @BeforeEach
    @AfterEach
    void cleanDatabase() throws Exception {
        try (Connection connection = connection(); var statement = connection.createStatement()) {
            dropIfExists(statement, "oracle_items");
            dropIfExists(statement, "schema_synchronizer_history");
        }
    }

    @Test
    void createsSerializesReplaysWidensIndexesAndReportsDestructiveDrift(@TempDir Path tempDir) throws Exception {
        SchemaSynchronizer synchronizer = synchronizer();
        SchemaDefinition initial = definition(List.of(
                new SchemaDefinition.ColumnDef("id", "NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL"),
                new SchemaDefinition.ColumnDef("label", "VARCHAR2(40) NOT NULL")));

        try (Connection connection = connection()) {
            assertThat(DatabaseDialect.detect(connection.getMetaData())).isEqualTo(DatabaseDialect.ORACLE);
            SchemaSynchronizationResult first = synchronizer.synchronizeWithResult(connection, initial);
            assertThat(first.tablesCreated()).isEqualTo(1);
        }
        try (Connection connection = connection()) {
            assertThat(synchronizer.synchronizeWithResult(connection, initial).changed()).isFalse();
        }

        SchemaDefinition additive = definition(List.of(
                new SchemaDefinition.ColumnDef("id", "NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL"),
                new SchemaDefinition.ColumnDef("label", "VARCHAR2(100) NOT NULL"),
                new SchemaDefinition.ColumnDef("notes", "VARCHAR2(255)")));
        try (Connection connection = connection()) {
            SchemaSynchronizationResult changed = synchronizer.synchronizeWithResult(connection, additive);
            assertThat(changed.columnsAdded()).isEqualTo(1);
            assertThat(changed.columnsAltered()).isEqualTo(1);
        }
        try (Connection connection = connection()) {
            assertThat(synchronizer.synchronizeWithResult(connection, additive).changed()).isFalse();
        }

        Path snapshot = tempDir.resolve("schema-definition.json");
        SchemaSnapshotWriter.main(new String[]{
                System.getProperty("schema.test.oracle.jdbc.url"),
                System.getProperty("schema.test.oracle.jdbc.user"),
                System.getProperty("schema.test.oracle.jdbc.password"),
                schema(),
                snapshot.toString()
        });
        SchemaDefinition serialized = new ObjectMapper().readValue(snapshot.toFile(), SchemaDefinition.class);
        assertThat(serialized.declaredDialect()).isEqualTo(DatabaseDialect.ORACLE);
        assertThat(serialized.tables()).containsKey("oracle_items");

        try (Connection connection = connection()) {
            assertThat(synchronizer.synchronizeWithResult(connection, initial).pendingSql())
                    .anyMatch(sql -> sql.toLowerCase(Locale.ROOT).contains("drop column notes"));
        }
    }

    private void dropIfExists(java.sql.Statement statement, String table) throws Exception {
        try {
            statement.execute("DROP TABLE " + table + " PURGE");
        } catch (Exception ignored) {
            // table may not exist
        }
    }

    private SchemaDefinition definition(List<SchemaDefinition.ColumnDef> columns) {
        return new SchemaDefinition(2, "oracle", Map.of("oracle_items",
                new SchemaDefinition.TableDef(
                        "CREATE TABLE oracle_items (id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "
                                + "label VARCHAR2(40) NOT NULL, PRIMARY KEY (id))",
                        columns,
                        List.of("CREATE INDEX idx_oracle_items_label ON oracle_items (label)"))),
                List.of());
    }

    private SchemaSynchronizer synchronizer() {
        return new SchemaSynchronizer(new ObjectMapper(), null, "",
                new SchemaSynchronizerOptions(schema(), "schema_synchronizer_history", 7_249_031_147L,
                        false, false, true));
    }

    private String schema() {
        String configured = System.getProperty("schema.test.oracle.jdbc.schema");
        if (configured != null && !configured.isBlank()) {
            return configured.toLowerCase(Locale.ROOT);
        }
        return System.getProperty("schema.test.oracle.jdbc.user").toLowerCase(Locale.ROOT);
    }

    private Connection connection() throws Exception {
        return DriverManager.getConnection(
                System.getProperty("schema.test.oracle.jdbc.url"),
                System.getProperty("schema.test.oracle.jdbc.user"),
                System.getProperty("schema.test.oracle.jdbc.password"));
    }
}
